/*
 * This file was automatically generated by EvoSuite
 */

package net.sf.jniinchi;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import net.sf.jniinchi.JniInchiStructure;
import net.sf.jniinchi.Main;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestMain {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      Main main0 = new Main();
      assertNotNull(main0);
  }

  @Test
  public void test1()  throws Throwable  {
      JniInchiStructure jniInchiStructure0 = Main.getTestMolecule();
      assertNotNull(jniInchiStructure0);
      assertEquals(6, jniInchiStructure0.getNumAtoms());
  }
}
